# http://docs.ansible.com/ansible/latest/playbooks_best_practices.html#directory-layout
---
# playbook.yml

- hosts: localhost
  connection: local
  gather_facts: yes
  become: true
  become_user: "root"
  vars_files:
    - "vars.yml"
    - "vars_ssm.yml"
  roles:
    - geerlingguy.firewall
    - geerlingguy.java
    - apolloclark.zookeeper
    - apolloclark.kafka
    - apolloclark.auditbeat
    - apolloclark.filebeat
    - apolloclark.packetbeat
    - apolloclark.metricbeat
    - apolloclark.heartbeat
    - apolloclark.osquery
