# http://docs.ansible.com/ansible/latest/galaxy.html#installing-multiple-roles-from-a-file
---
- src: geerlingguy.firewall
- src: geerlingguy.java               # https://github.com/geerlingguy/ansible-role-java
- src: apolloclark.zookeeper          # https://github.com/apolloclark/ansible-role-zookeeper
- src: apolloclark.kafka              # https://github.com/apolloclark/ansible-role-kafka
- src: apolloclark.auditbeat          # https://github.com/apolloclark/ansible-role-auditbeat
- src: apolloclark.filebeat           # https://github.com/apolloclark/ansible-role-filebeat
- src: apolloclark.heartbeat          # https://github.com/apolloclark/ansible-role-heartbeat
- src: apolloclark.metricbeat         # https://github.com/apolloclark/ansible-role-metricbeat
- src: apolloclark.packetbeat         # https://github.com/apolloclark/ansible-role-packetbeat
- src: apolloclark.osquery            # https://github.com/apolloclark/ansible-role-osquery
