# http://docs.ansible.com/ansible/latest/playbooks_variables.html#variable-file-separation
---
hostname: all

# geerlingguy/firewall
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "2181" # Zookeeper
  - "9092" # Kafka

# geerlingguy/java
java_packages:
  - openjdk-8-jre



kafka_ip: "127.0.0.1"
es_ip: "127.0.0.1"



# apolloclark/kafka
kafka:
  version: "2.0.0"
  scala_version: "2.11"

# apolloclark/heartbeat
heartbeat:
  version: "6.4.2"
  monitors:
    http:
      schedule: "'@every 5s'"
      urls: '["http://localhost:80", "http://localhost:5601"]'
  output:
    kafka:
      enabled: true
      hosts:
       - "{{ kafka_ip }}:9092"

# apolloclark/metricbeat
metricbeat:
  version: "6.4.2"
  output:
    kafka:
      enabled: true
      hosts:
       - "{{ kafka_ip }}:9092"

# apolloclark/packetbeat
packetbeat:
  version: "6.4.2"
  protocols:
    tcp:
      enabled: true
      ports: '[22,2181,9092]'
  output:
    kafka:
      enabled: true
      hosts:
       - "{{ kafka_ip }}:9092"

# apolloclark/filebeat
filebeat:
  version: "6.4.2"
  output:
    kafka:
      enabled: true
      hosts:
       - "{{ kafka_ip }}:9092"

# apolloclark/auditbeat
auditbeat:
  version: "6.4.2"
  output:
    kafka:
      enabled: true
      hosts:
       - "{{ kafka_ip }}:9092"
