# http://docs.ansible.com/ansible/latest/playbooks_variables.html#variable-file-separation
---
hostname: all

# geerlingguy/firewall
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "2181" # Zookeeper
  - "5044" # Logstash
  - "5601" # Kibana
  - "9092" # Kafka
  - "9200" # Elasticsearch
  - "9300" # Elasticsearch

# geerlingguy/java
java_packages:
  - openjdk-8-jre



es_ip: "127.0.0.1"
kafka_ip: "127.0.0.1"
logstash_ip: "127.0.0.1"
kibana_ip: "127.0.0.1"



# apolloclark/crontab
crontab:
  global:
    - "@reboot root /home/vagrant/restart_elk_services.sh"

# apolloclark/kafka
kafka:
  version: "2.0.0"
  scala_version: "2.11"

# apolloclark/heartbeat
heartbeat:
  version: "6.4.2"
  monitors:
    http:
      schedule: "'@every 5s'"
      urls: '["http://localhost:80", "http://localhost:5601"]'
  output:
    elasticsearch:
      enabled: false
      hosts:
       - "{{ es_ip }}:9200"
    kafka:
      enabled: true
      hosts:
       - "{{ kafka_ip }}:9092"
  setup:
    dashboards:
      enabled: true
    template:
      enabled: true
    kibana:
      host: "{{ kibana_ip }}:5601"

# apolloclark/metricbeat
metricbeat:
  version: "6.4.2"
  output:
    elasticsearch:
      enabled: false
      hosts:
       - "{{ es_ip }}:9200"
    kafka:
      enabled: true
      hosts:
       - "{{ kafka_ip }}:9092"
  setup:
    dashboards:
      enabled: true
    template:
      enabled: true
    kibana:
      host: "{{ kibana_ip }}:5601"

# apolloclark/packetbeat
packetbeat:
  version: "6.4.2"
  protocols:
    http:
      enabled: true
      ports: '[80,5601,9200]'
  output:
    elasticsearch:
      enabled: false
      hosts:
       - "{{ es_ip }}:9200"
    kafka:
      enabled: true
      hosts:
       - "{{ kafka_ip }}:9092"
  setup:
    dashboards:
      enabled: true
    template:
      enabled: true
    kibana:
      host: "{{ kibana_ip }}:5601"

# apolloclark/filebeat
filebeat:
  version: "6.4.2"
  output:
    elasticsearch:
      enabled: false
      hosts:
       - "{{ es_ip }}:9200"
    kafka:
      enabled: true
      hosts:
       - "{{ kafka_ip }}:9092"
  setup:
    dashboards:
      enabled: true
    template:
      enabled: true
    kibana:
      host: "{{ kibana_ip }}:5601"

# apolloclark/auditbeat
auditbeat:
  version: "6.4.2"
  output:
    elasticsearch:
      enabled: false
      hosts:
       - "{{ es_ip }}:9200"
    kafka:
      enabled: true
      hosts:
       - "{{ kafka_ip }}:9092"
  setup:
    dashboards:
      enabled: true
    template:
      enabled: true
    kibana:
      host: "{{ kibana_ip }}:5601"

# apolloclark/elasticsearch
# BINDING TO 0.0.0.0 IS DANGEROUS, UNLESS YOU ENFORCE FIREWALL RULES
# OR USE X-PACK
elasticsearch:
  version: "6.4.2"
  network:
    host: "0.0.0.0"
    bind_host: "0.0.0.0"
    publish_host: "_local_"
  action:
    destructive_requires_name: false
  install_plugins: []

# apolloclark/logstash
logstash:
  version: "6.4.2"
  input_conf: "{{ playbook_dir }}/files/10-beats-input.conf"
  filter_conf: "{{ playbook_dir }}/files/20-syslog-filter.conf"
  output_conf: "{{ playbook_dir }}/files/30-elasticsearch-output.conf"

# apolloclark/kibana
kibana:
  version: "6.4.2"
