# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

    # Ubuntu 16.04 Xenial LTS 64-bit
    config.vm.box = "apolloclark/ubuntu16.04-elk"
    # config.vm.box_version = "20170926"

    # VirtualBox Provider-specific configuration
    config.vm.provider "virtualbox" do |vb, override|

        # set the VM name
        vb.name = "packer-aws-elk"

        # set the CPU, memory, graphics
        # @see https://www.virtualbox.org/manual/ch08.html
        vb.gui = false
        vb.memory = "4096"
        vb.cpus = 1

        # Share a folder to the guest VM, types: docker, nfs, rsync, smb, virtualbox
        # Windows supports: smb
        # Mac supports: rsync, nfs
        # override.vm.synced_folder host_folder.to_s, guest_folder.to_s, type: "smb"
        override.vm.synced_folder "./", "/vagrant"
            # owner: "vagrant", group: "vagrant",
            # mount_options: ['dmode=777','fmode=777']

        # Create a forwarded port mapping which allows access to a specific port
        # within the machine from a port on the host machine. In the example below,
        # accessing "localhost:8080" will access port 80 on the guest machine.
        # https://www.vagrantup.com/docs/networking/forwarded_ports.html
        override.vm.network "forwarded_port", guest: 5601, host: 5601, auto_correct: true
    end

    # VirtualBox Provider-specific configuration
    config.vm.provider "vmware" do |vb, override|

        # set the VM name
        vb.name = "packer-aws-elk"

        # set the CPU, memory, graphics
        # @see https://www.virtualbox.org/manual/ch08.html
        vb.gui = false
        vb.vmx["memsize"] = "4096"
        vb.vmx["numvcpus"] = "1"

        # Share a folder to the guest VM, types: docker, nfs, rsync, smb, virtualbox
        # Windows supports: smb
        # Mac supports: rsync, nfs
        # override.vm.synced_folder host_folder.to_s, guest_folder.to_s, type: "smb"
        #override.vm.synced_folder "./", "/vagrant"
            # owner: "vagrant", group: "vagrant",
            # mount_options: ['dmode=777','fmode=777']

        # Create a forwarded port mapping which allows access to a specific port
        # within the machine from a port on the host machine. In the example below,
        # accessing "localhost:8080" will access port 80 on the guest machine.
        # https://www.vagrantup.com/docs/networking/forwarded_ports.html
        override.vm.network "forwarded_port", guest: 5601, host: 5601, auto_correct: true
    end

    # setup local apt-get cache
    if Vagrant.has_plugin?("vagrant-cachier")
        # Configure cached packages to be shared between instances of the same base box.
        # https://github.com/fgrehm/vagrant-cachier
        # More info on the "Usage" link above
        override.cache.scope = :box
    end
end
